# 300+ hardcoded "This or That" questions for the compatibility game
QUESTIONS = [
    "Coffee ☕ or Tea 🍵?",
    "Dogs 🐕 or Cats 🐱?",
    "Summer ☀️ or Winter ❄️?",
    "Beach 🏖️ or Mountains 🏔️?",
    "Movies 🎬 or Books 📚?",
    "Pizza 🍕 or Burgers 🍔?",
    "Morning 🌅 or Night 🌙?",
    "Sweet 🍭 or Salty 🥨?",
    "Texting 📱 or Calling ☎️?",
    "Indoor 🏠 or Outdoor 🌳?",
    "City 🏙️ or Countryside 🌾?",
    "Hot 🔥 or Cold 🧊?",
    "Chocolate 🍫 or Vanilla 🍦?",
    "Rain 🌧️ or Snow ❄️?",
    "Netflix 📺 or YouTube 📽️?",
    "Early Bird 🐦 or Night Owl 🦉?",
    "Spotify 🎵 or Apple Music 🎶?",
    "Android 🤖 or iPhone 📱?",
    "Pasta 🍝 or Rice 🍚?",
    "Car 🚗 or Bike 🚲?",
    "Comedy 😂 or Drama 🎭?",
    "Hiking 🥾 or Swimming 🏊?",
    "Board Games 🎲 or Video Games 🎮?",
    "Cooking 👨‍🍳 or Ordering Out 🛍️?",
    "Instagram 📸 or TikTok 🎵?",
    "Sneakers 👟 or Dress Shoes 👞?",
    "T-shirt 👕 or Button-up 👔?",
    "Jeans 👖 or Shorts 🩳?",
    "Horror 👻 or Romance 💕?",
    "Action 💥 or Adventure 🗺️?",
    "Documentary 📹 or Fiction 📖?",
    "Gym 💪 or Home Workout 🏠?",
    "Running 🏃 or Walking 🚶?",
    "Team Sports ⚽ or Individual Sports 🎾?",
    "Plane ✈️ or Train 🚂?",
    "Hotel 🏨 or Camping ⛺?",
    "Sushi 🍣 or Tacos 🌮?",
    "Spicy 🌶️ or Mild 🥛?",
    "Beer 🍺 or Wine 🍷?",
    "Water 💧 or Soda 🥤?",
    "Breakfast 🥞 or Dinner 🍽️?",
    "Fruits 🍎 or Vegetables 🥕?",
    "Meat 🥩 or Vegetarian 🥗?",
    "Ice Cream 🍨 or Cake 🎂?",
    "Cookies 🍪 or Brownies 🍫?",
    "Juice 🧃 or Smoothie 🥤?",
    "Fast Food 🍟 or Fine Dining 🍽️?",
    "Homemade 🏠 or Restaurant 🏪?",
    "Breakfast in Bed 🛏️ or Picnic 🧺?",
    "Barbecue 🔥 or Potluck 🥘?",
    "Rock 🎸 or Pop 🎤?",
    "Jazz 🎺 or Classical 🎼?",
    "Live Concert 🎵 or Studio Album 💿?",
    "Dancing 💃 or Singing 🎤?",
    "Guitar 🎸 or Piano 🎹?",
    "Podcast 🎧 or Music 🎵?",
    "Headphones 🎧 or Speakers 🔊?",
    "Vinyl 💿 or Digital 📱?",
    "Festival 🎪 or Intimate Venue 🎭?",
    "Band 🎸 or Solo Artist 🎤?",
    "Fiction 📚 or Non-fiction 📖?",
    "Mystery 🔍 or Romance 💕?",
    "Sci-fi 🚀 or Fantasy 🧙?",
    "Physical Book 📚 or E-book 📱?",
    "Library 📚 or Bookstore 🏪?",
    "Biography 👤 or Autobiography ✍️?",
    "Poetry 📝 or Prose 📖?",
    "Magazine 📰 or Newspaper 📃?",
    "Comic Books 📚 or Graphic Novels 📖?",
    "Reading 📚 or Writing ✍️?",
    "Marvel 🦸 or DC 🦹?",
    "Star Wars 🌟 or Star Trek 🚀?",
    "Lord of the Rings 💍 or Harry Potter ⚡?",
    "Disney 🏰 or Pixar 🎭?",
    "Comedy Show 😂 or Drama Series 🎭?",
    "Reality TV 📺 or Scripted Shows 🎬?",
    "News 📰 or Entertainment 🎪?",
    "Sports 🏈 or Movies 🎬?",
    "Sitcom 😄 or Thriller 😱?",
    "Binge Watching 📺 or Weekly Episodes 📅?",
    "Subtitles 📝 or Dubbing 🎤?",
    "Cinema 🎬 or Home Theater 🏠?",
    "3D 🕶️ or 2D 👀?",
    "Premiere 🎉 or Later Viewing 📅?",
    "Popcorn 🍿 or Candy 🍬?",
    "Front Row 🎪 or Back Row 🎭?",
    "Matinee 🌅 or Evening Show 🌙?",
    "Group Viewing 👥 or Solo 🧍?",
    "Sunny ☀️ or Cloudy ☁️?",
    "Spring 🌸 or Fall 🍂?",
    "Humid 💦 or Dry 🏜️?",
    "Windy 💨 or Calm 🧘?",
    "Thunderstorm ⛈️ or Clear Skies ☀️?",
    "Sunrise 🌅 or Sunset 🌅?",
    "Full Moon 🌕 or New Moon 🌑?",
    "Stars ✨ or Clouds ☁️?",
    "Rainbow 🌈 or Lightning ⚡?",
    "Seasons 🍂 or Year-round Same 🔄?",
    "Football 🏈 or Basketball 🏀?",
    "Soccer ⚽ or Baseball ⚾?",
    "Tennis 🎾 or Golf ⛳?",
    "Swimming 🏊 or Running 🏃?",
    "Cycling 🚴 or Walking 🚶?",
    "Yoga 🧘 or Weightlifting 🏋️?",
    "Cardio 💓 or Strength Training 💪?",
    "Group Fitness 👥 or Solo Workout 🧍?",
    "Outdoor Sports 🌳 or Indoor Sports 🏠?",
    "Professional Sports 🏆 or Amateur 🥇?",
    "Playing 🎮 or Watching 👀?",
    "Team Captain 👑 or Team Player 🤝?",
    "Competition 🏆 or Fun 🎉?",
    "Training 💪 or Game Day 🏈?",
    "Early Morning ⏰ or Late Night 🌙?",
    "Car 🚗 or Public Transport 🚌?",
    "Walking 🚶 or Driving 🚗?",
    "Uber 🚗 or Taxi 🚕?",
    "Motorcycle 🏍️ or Scooter 🛴?",
    "Road Trip 🛣️ or Flying ✈️?",
    "Window Seat 🪟 or Aisle Seat 🚶?",
    "GPS 📱 or Paper Map 🗺️?",
    "Highway 🛣️ or Scenic Route 🌄?",
    "Rush Hour 🚦 or Off-peak 🛣️?",
    "Parking Lot 🅿️ or Street Parking 🚗?",
    "Manual 🕹️ or Automatic 🔄?",
    "Gas ⛽ or Electric 🔋?",
    "Sedan 🚗 or SUV 🚙?",
    "New Car 🆕 or Used Car 🔄?",
    "Lease 📄 or Buy 💰?",
    "Cash 💵 or Credit Card 💳?",
    "Online Shopping 🛒 or In-store 🏪?",
    "Brand Name 🏷️ or Generic 🏪?",
    "Sale 🏷️ or Full Price 💰?",
    "Quality 🌟 or Quantity 📦?",
    "Splurge 💸 or Save 💰?",
    "Investment 📈 or Spending 💸?",
    "Budgeting 📊 or Spontaneous 🎲?",
    "Cash 💵 or Digital Payment 📱?",
    "Coupons 🎟️ or Regular Price 💰?",
    "Luxury 💎 or Practical 🔧?",
    "Impulse Buy 🛒 or Planned Purchase 📝?",
    "Warranty 🛡️ or Risk It 🎲?",
    "Reviews 📝 or Trust 🤝?",
    "Compare Prices 📊 or First Option 1️⃣?",
    "Black Friday 🛍️ or Regular Shopping 🏪?",
    "Makeup 💄 or Natural 🌿?",
    "Long Hair 💇‍♀️ or Short Hair ✂️?",
    "Beard 🧔 or Clean Shaven 🪒?",
    "Tattoos 🎨 or No Tattoos ❌?",
    "Piercings 💎 or No Piercings ❌?",
    "Casual 👕 or Formal 👔?",
    "Bright Colors 🌈 or Neutral Colors ⚪?",
    "Patterns 📐 or Solid Colors 🟦?",
    "Vintage 👗 or Modern 🆕?",
    "Designer 💎 or Thrift Store 🏪?",
    "Comfortable 🛋️ or Stylish 💃?",
    "Accessories 💍 or Minimal 🤏?",
    "High Heels 👠 or Flats 🥿?",
    "Jewelry 💍 or No Jewelry ❌?",
    "Perfume 🌸 or Natural Scent 🌿?",
    "Salon 💇 or DIY 🏠?",
    "House 🏠 or Apartment 🏢?",
    "Rent 🏠 or Own 🏡?",
    "City Center 🏙️ or Suburbs 🏘️?",
    "High Rise 🏢 or Ground Floor 🏠?",
    "Balcony 🏞️ or Backyard 🌳?",
    "Open Floor Plan 🏠 or Separate Rooms 🚪?",
    "Modern 🆕 or Traditional 🏛️?",
    "Furnished 🛋️ or Unfurnished 📦?",
    "Roommates 👥 or Live Alone 🧍?",
    "Pet-friendly 🐕 or No Pets ❌?",
    "Garage 🚗 or Street Parking 🅿️?",
    "Garden 🌻 or No Garden ❌?",
    "Pool 🏊 or No Pool ❌?",
    "Elevator 🛗 or Stairs 🪜?",
    "Doorman 👨‍💼 or Self-service 🗝️?",
    "Near Work 🏢 or Near Family 👨‍👩‍👧‍👦?",
    "Facebook 👥 or Instagram 📸?",
    "Twitter 🐦 or LinkedIn 💼?",
    "WhatsApp 💬 or Telegram 📱?",
    "Snapchat 👻 or TikTok 🎵?",
    "Reddit 🤖 or Discord 🎮?",
    "YouTube 📺 or Twitch 🎮?",
    "Email 📧 or Text 📱?",
    "Video Call 📹 or Voice Call 📞?",
    "Group Chat 👥 or One-on-One 👤?",
    "Emojis 😊 or Words 📝?",
    "Stories 📖 or Posts 📰?",
    "Public Profile 🌍 or Private 🔒?",
    "Follow Back ↩️ or Selective 🎯?",
    "Daily Posting 📅 or Occasional 🎲?",
    "Likes 👍 or Comments 💬?",
    "Trending 📈 or Personal Interest 👤?",
    "Influencers 🌟 or Friends 👥?",
    "Live Streaming 📹 or Pre-recorded 📹?",
    "Gaming Content 🎮 or Lifestyle 🏠?",
    "Educational 📚 or Entertainment 🎪?",
    "Desktop 🖥️ or Laptop 💻?",
    "Mac 🍎 or PC 🖥️?",
    "iOS 📱 or Android 🤖?",
    "Chrome 🌐 or Safari 🧭?",
    "Wired ⚡ or Wireless 📶?",
    "Keyboard ⌨️ or Touchscreen 📱?",
    "Mouse 🖱️ or Trackpad 👆?",
    "Multiple Monitors 🖥️🖥️ or Single Monitor 🖥️?",
    "Cloud Storage ☁️ or Local Storage 💾?",
    "Automatic Updates 🔄 or Manual 🤏?",
    "Password Manager 🔐 or Memory 🧠?",
    "Antivirus 🛡️ or Built-in Security 🔒?",
    "Gaming PC 🎮 or Console 🕹️?",
    "VR 🥽 or Traditional Gaming 🎮?",
    "Single Player 🧍 or Multiplayer 👥?",
    "Strategy 🧠 or Action 💥?",
    "Mobile Games 📱 or PC Games 🖥️?",
    "Free-to-Play 🆓 or Premium 💰?",
    "Indie Games 🎨 or AAA Titles 🌟?",
    "Retro Games 👾 or Modern Games 🆕?",
    "Competitive 🏆 or Casual 😌?",
    "RPG ⚔️ or FPS 🔫?",
    "Simulation 🏗️ or Arcade 🕹️?",
    "Story Mode 📖 or Endless 🔄?",
    "Co-op 🤝 or PvP ⚔️?",
    "Controller 🎮 or Keyboard & Mouse ⌨️🖱️?",
    "Physical Copy 💿 or Digital Download 📥?",
    "Pre-order 📅 or Wait for Reviews 📝?",
    "Early Bird 🐦 or Night Owl 🦉?",
    "5 AM Wake-up ⏰ or Sleep In 😴?",
    "Alarm Clock ⏰ or Natural Wake-up 🌅?",
    "Snooze Button 😴 or Get Up Immediately ⚡?",
    "Coffee First ☕ or Shower First 🚿?",
    "Morning Exercise 🏃 or Evening Exercise 🌙?",
    "Breakfast 🥞 or Skip Breakfast ⏭️?",
    "News 📰 or Music 🎵?",
    "Planning the Day 📝 or Go with the Flow 🌊?",
    "Morning Person ☀️ or Not a Morning Person 🌙?",
    "Meditation 🧘 or Jump Right In 🏃?",
    "Quiet Morning 🤫 or Active Morning 🏃?",
    "Routine 🔄 or Spontaneous 🎲?",
    "Weekend Sleep-in 😴 or Same Schedule 📅?",
    "Morning Motivation 💪 or Need Time to Wake Up 😴?",
    "10 PM Bedtime 🛏️ or Midnight Bedtime 🌙?",
    "Reading Before Bed 📚 or Screen Time 📱?",
    "Hot Shower 🔥 or Cold Shower 🥶?",
    "Brushing Teeth 🦷 or Mouthwash 💧?",
    "Pajamas 👔 or Sleep Clothes 👕?",
    "Complete Darkness 🌑 or Night Light 💡?",
    "Fan 🌪️ or No Fan ❌?",
    "Multiple Pillows 🛏️ or One Pillow 🛏️?",
    "Firm Mattress 🛏️ or Soft Mattress 🛏️?",
    "Sleep Music 🎵 or Silence 🤫?",
    "Early Bedtime 🌅 or Late Bedtime 🌙?",
    "Weekend Nap 😴 or Stay Awake 👁️?",
    "Sleep Mask 🥽 or No Mask 👁️?",
    "White Noise 🌊 or Natural Sounds 🦆?",
    "Phone Charging Nearby 📱 or Far Away 🔌?",
    "Room Temperature 🌡️ or Bundled Up 🧥?"
]
